### ISSUE TITLE
Migration of fenics to pyiron_continuum 

### ISSUE THREAD

**Issue by jan-janssen** [pyiron/pyiron_continuum#1]
```
======================================================================
9
ERROR: test_page_5 (fenics.test_tutorials.TestFenicsTutorials)
10
----------------------------------------------------------------------
11
Traceback (most recent call last):
12
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/tests_integration/fenics/test_tutorials.py", line 35, in test_page_5
13
    job = self.pr.create.job.Fenics('poisson', delete_existing_job=True)
14
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 152, in wrapper
15
    return job.create(job_name=job_name, delete_existing_job=delete_existing_job)
16
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 178, in create
17
    return JobType(
18
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 56, in __new__
19
    job_class = cls.convert_str_to_class(
20
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 104, in convert_str_to_class
21
    job_module = importlib.import_module(job_class_dict[job_class_name])
22
  File "/usr/share/miniconda/envs/test/lib/python3.8/importlib/__init__.py", line 127, in import_module
23
    return _bootstrap._gcd_import(name[level:], package, level)
24
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
25
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
26
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
27
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
28
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
29
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
30
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/job/generic.py", line 17, in <module>
31
    from pyiron_continuum.fenics.factory import DomainFactory, BoundaryConditionFactory
32
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/factory.py", line 64, in <module>
33
    class UnitMeshFactory(PyironFactory):
34
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/factory.py", line 67, in UnitMeshFactory
35
    square.__doc__ = FEN.UnitSquareMesh.__doc__
36
AttributeError: module 'fenics' has no attribute 'UnitSquareMesh'
37

38
======================================================================
39
ERROR: test_page_6 (fenics.test_tutorials.TestFenicsTutorials)
40
----------------------------------------------------------------------
41
Traceback (most recent call last):
42
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/tests_integration/fenics/test_tutorials.py", line 49, in test_page_6
43
    job = self.pr.create.job.Fenics('membrane', delete_existing_job=True)
44
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 152, in wrapper
45
    return job.create(job_name=job_name, delete_existing_job=delete_existing_job)
46
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 178, in create
47
    return JobType(
48
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 56, in __new__
49
    job_class = cls.convert_str_to_class(
50
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 104, in convert_str_to_class
51
    job_module = importlib.import_module(job_class_dict[job_class_name])
52
  File "/usr/share/miniconda/envs/test/lib/python3.8/importlib/__init__.py", line 127, in import_module
53
    return _bootstrap._gcd_import(name[level:], package, level)
54
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
55
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
56
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
57
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
58
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
59
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
60
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/job/generic.py", line 17, in <module>
61
    from pyiron_continuum.fenics.factory import DomainFactory, BoundaryConditionFactory
62
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/factory.py", line 64, in <module>
63
    class UnitMeshFactory(PyironFactory):
64
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/factory.py", line 67, in UnitMeshFactory
65
    square.__doc__ = FEN.UnitSquareMesh.__doc__
66
AttributeError: module 'fenics' has no attribute 'UnitSquareMesh'
67

68
======================================================================
69
ERROR: test_page_7_gaussian (fenics.test_tutorials.TestFenicsTutorials)
70
----------------------------------------------------------------------
71
Traceback (most recent call last):
72
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/tests_integration/fenics/test_tutorials.py", line 89, in test_page_7_gaussian
73
    job = self.pr.create.job.Fenics('gauss', delete_existing_job=True)
74
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 152, in wrapper
75
    return job.create(job_name=job_name, delete_existing_job=delete_existing_job)
76
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 178, in create
77
    return JobType(
78
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 56, in __new__
79
    job_class = cls.convert_str_to_class(
80
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 104, in convert_str_to_class
81
    job_module = importlib.import_module(job_class_dict[job_class_name])
82
  File "/usr/share/miniconda/envs/test/lib/python3.8/importlib/__init__.py", line 127, in import_module
83
    return _bootstrap._gcd_import(name[level:], package, level)
84
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
85
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
86
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
87
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
88
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
89
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
90
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/job/generic.py", line 17, in <module>
91
    from pyiron_continuum.fenics.factory import DomainFactory, BoundaryConditionFactory
92
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/factory.py", line 64, in <module>
93
    class UnitMeshFactory(PyironFactory):
94
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/factory.py", line 67, in UnitMeshFactory
95
    square.__doc__ = FEN.UnitSquareMesh.__doc__
96
AttributeError: module 'fenics' has no attribute 'UnitSquareMesh'
97

98
======================================================================
99
ERROR: test_page_7_heat (fenics.test_tutorials.TestFenicsTutorials)
100
----------------------------------------------------------------------
101
Traceback (most recent call last):
102
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/tests_integration/fenics/test_tutorials.py", line 65, in test_page_7_heat
103
    job = self.pr.create.job.Fenics('heat', delete_existing_job=True)
104
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 152, in wrapper
105
    return job.create(job_name=job_name, delete_existing_job=delete_existing_job)
106
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 178, in create
107
    return JobType(
108
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 56, in __new__
109
    job_class = cls.convert_str_to_class(
110
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 104, in convert_str_to_class
111
    job_module = importlib.import_module(job_class_dict[job_class_name])
112
  File "/usr/share/miniconda/envs/test/lib/python3.8/importlib/__init__.py", line 127, in import_module
113
    return _bootstrap._gcd_import(name[level:], package, level)
114
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
115
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
116
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
117
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
118
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
119
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
120
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/job/generic.py", line 17, in <module>
121
    from pyiron_continuum.fenics.factory import DomainFactory, BoundaryConditionFactory
122
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/factory.py", line 64, in <module>
123
    class UnitMeshFactory(PyironFactory):
124
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/factory.py", line 67, in UnitMeshFactory
125
    square.__doc__ = FEN.UnitSquareMesh.__doc__
126
AttributeError: module 'fenics' has no attribute 'UnitSquareMesh'
127

128
======================================================================
129
ERROR: test_page_8 (fenics.test_tutorials.TestFenicsTutorials)
130
----------------------------------------------------------------------
131
Traceback (most recent call last):
132
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/tests_integration/fenics/test_tutorials.py", line 110, in test_page_8
133
    job = self.pr.create.job.Fenics('poisson_nonlinear', delete_existing_job=True)
134
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 152, in wrapper
135
    return job.create(job_name=job_name, delete_existing_job=delete_existing_job)
136
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 178, in create
137
    return JobType(
138
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 56, in __new__
139
    job_class = cls.convert_str_to_class(
140
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 104, in convert_str_to_class
141
    job_module = importlib.import_module(job_class_dict[job_class_name])
142
  File "/usr/share/miniconda/envs/test/lib/python3.8/importlib/__init__.py", line 127, in import_module
143
    return _bootstrap._gcd_import(name[level:], package, level)
144
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
145
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
146
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
147
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
148
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
149
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
150
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/job/generic.py", line 17, in <module>
151
    from pyiron_continuum.fenics.factory import DomainFactory, BoundaryConditionFactory
152
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/factory.py", line 64, in <module>
153
    class UnitMeshFactory(PyironFactory):
154
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/factory.py", line 67, in UnitMeshFactory
155
    square.__doc__ = FEN.UnitSquareMesh.__doc__
156
AttributeError: module 'fenics' has no attribute 'UnitSquareMesh'
157

158
======================================================================
159
ERROR: test_page_9 (fenics.test_tutorials.TestFenicsTutorials)
160
----------------------------------------------------------------------
161
Traceback (most recent call last):
162
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/tests_integration/fenics/test_tutorials.py", line 146, in test_page_9
163
    job = self.pr.create.job.FenicsLinearElastic('linear_elasticity', delete_existing_job=True)
164
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 152, in wrapper
165
    return job.create(job_name=job_name, delete_existing_job=delete_existing_job)
166
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 178, in create
167
    return JobType(
168
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 56, in __new__
169
    job_class = cls.convert_str_to_class(
170
  File "/usr/share/miniconda/envs/test/lib/python3.8/site-packages/pyiron_base/job/jobtype.py", line 104, in convert_str_to_class
171
    job_module = importlib.import_module(job_class_dict[job_class_name])
172
  File "/usr/share/miniconda/envs/test/lib/python3.8/importlib/__init__.py", line 127, in import_module
173
    return _bootstrap._gcd_import(name[level:], package, level)
174
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
175
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
176
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
177
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
178
  File "<frozen importlib._bootstrap_external>", line 783, in exec_module
179
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
180
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/job/elastic.py", line 9, in <module>
181
    from pyiron_continuum.fenics.job.generic import Fenics
182
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/job/generic.py", line 17, in <module>
183
    from pyiron_continuum.fenics.factory import DomainFactory, BoundaryConditionFactory
184
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/factory.py", line 64, in <module>
185
    class UnitMeshFactory(PyironFactory):
186
  File "/home/runner/work/pyiron_continuum/pyiron_continuum/pyiron_continuum/fenics/factory.py", line 67, in UnitMeshFactory
187
    square.__doc__ = FEN.UnitSquareMesh.__doc__
188
AttributeError: module 'fenics' has no attribute 'UnitSquareMesh'
```

**Comment by liamhuber** [comment]
Some sort of library version error. I guess at some point you had to use `dolphin.cpp.UnitSquareMesh` or something like that, and later this got moved into `fenics`.
